{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "e875711e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "By Default Language is German/ Deutsch wird automatisch gewählt\n",
      "Enter E or e for English / geben Sie D oer d für deutsch ein\n",
      "ef\n"
     ]
    }
   ],
   "source": [
    "from tkinter import *\n",
    "import random\n",
    "import time\n",
    "from tkinter import ttk\n",
    "from tkinter import messagebox\n",
    "import sqlite3\n",
    "from tkinter import *\n",
    "\n",
    "\n",
    "#It is definition of System\n",
    "def system(n):\n",
    "    root = Tk()\n",
    "    root.geometry(\"1350x800\")\n",
    "    root.title(\"Café der Liebe\")\n",
    "    root.configure(background='papayawhip')\n",
    "    Tops=Frame(root,width= 550, height=175, bd=5, relief='flat')\n",
    "    Tops.pack(side=TOP)\n",
    "    f1=Frame(root,width= 781, height=600, bd=2, relief='flat')\n",
    "    f1.pack(side=LEFT)\n",
    "    f2=Frame(root,width= 500, height=601, bd=2, relief='flat')\n",
    "    f2.pack(side=RIGHT)\n",
    "    \n",
    "    f1a=Frame(f1,width= 780, height=300, bd=1, relief='ridge')\n",
    "    f1a.pack(side=TOP)\n",
    "    f2a=Frame(f1,width= 780, height=300, bd=1, relief='ridge')\n",
    "    f2a.pack(side=BOTTOM)\n",
    "    \n",
    "    ft2=Frame(f2,width=500,height=601,bd=1,relief='flat')\n",
    "    ft2.pack(side=TOP)\n",
    "    fb2=Frame(f2,width=500,height=50,bd=1,relief='flat')\n",
    "    fb2.pack(side=BOTTOM)\n",
    "       \n",
    "    f1aa=Frame(f1a,width= 400, height=300, bd=1, relief='ridge')\n",
    "    f1aa.pack(side=LEFT)\n",
    "    f2aa=Frame(f2a,width= 480, height=300, bd=1, relief='ridge')\n",
    "    f2aa.pack(side=LEFT)\n",
    "    f1ab=Frame(f1a,width= 300, height=300, bd=0, relief='ridge')\n",
    "    f1ab.pack(side=RIGHT)\n",
    "    f2ab=Frame(f2a,width= 300, height=300, bd=0, relief='ridge')\n",
    "    f2ab.pack(side=RIGHT)\n",
    "    Tops.configure(background='beige')\n",
    "    f1.configure(background='papayawhip')\n",
    "    f2.configure(background='papayawhip')\n",
    "    lblInfo=Label(Tops, font=('Segoe Print',40,'bold'),text='Café der Liebe',fg='chocolate4',bg='burlywood1')\n",
    "    lblInfo.grid(row=0,column=0)\n",
    "    \n",
    "    if(n=='E' or n=='e'):\n",
    "        def qExit():\n",
    "            qExit=messagebox.askyesno(\"Quit System\",\"Do you want to quit?\")\n",
    "            if qExit>0:\n",
    "                root.destroy()\n",
    "                return\n",
    "        def Receipt():\n",
    "            txtReceipt.delete(\"1.0\",END)\n",
    "            x=random.randint(10900,500876)\n",
    "            randomRef=str(x)\n",
    "            Receipt_Ref.set(\"RCC\"+randomRef)\n",
    "            txtReceipt.insert(END,'Receipt Ref:\\t\\t'+Receipt_Ref.get()+'\\t\\t'+DateofOrder.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Items\\t\\t\\t'+'No. of Items \\n')\n",
    "            txtReceipt.insert(END,'Latte\\t\\t\\t'+E_m1.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Flat White\\t\\t\\t'+E_m2.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Cappuccino\\t\\t\\t'+E_m3.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Espresso\\t\\t\\t'+E_m4.get()+'\\n')\n",
    "            txtReceipt.insert(END,'White Hot Chocolate\\t\\t\\t'+E_m5.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Matcha Tea\\t\\t\\t'+E_m6.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Chai\\t\\t\\t'+E_m7.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Tea Lemonade\\t\\t\\t'+E_m8.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Cool Lime\\t\\t\\t'+E_m9.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Vanilla Cake\\t\\t\\t'+E_m10.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Chocolate Cake\\t\\t\\t'+E_m11.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Strawberry and Vanilla Cake\\t\\t\\t'+E_m12.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Cost of Drinks:\\t'+CostofDrinks.get()+'\\t   Tax Paid:\\t'+PaidTax.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Cost of Cakes:\\t'+CostofCakes.get()+'\\t  SubTotal:\\t'+SubTotal.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Service Charge:\\t'+CostofDrinks.get()+'\\t   Total Cost:\\t'+TotalCost.get()+'\\n')\n",
    "            \n",
    "        def CostofItem():\n",
    "            i1=float(E_m1.get())\n",
    "            i2=float(E_m2.get())\n",
    "            i3=float(E_m3.get())\n",
    "            i4=float(E_m4.get())\n",
    "            i5=float(E_m5.get())\n",
    "            i6=float(E_m6.get())\n",
    "            i7=float(E_m7.get())\n",
    "            i8=float(E_m8.get())\n",
    "            i9=float(E_m9.get())\n",
    "            i10=float(E_m10.get())\n",
    "            i11=float(E_m11.get())\n",
    "            i12=float(E_m12.get())\n",
    "            \n",
    "            PriceofDrinks=(i1*200)+(i2*210)+(i3*180)+(i4*100)+(i5*300)+(i6*340)+(i7*120)+(i8*140)+(i9*80)\n",
    "            PriceofCakes=(i10*720)+(i11*840)+(i12*1200)\n",
    "            \n",
    "            DrinksPrice='₹',str('%.2f'%(PriceofDrinks))\n",
    "            CakesPrice='₹',str('%.2f'%(PriceofCakes))\n",
    "            CostofDrinks.set(DrinksPrice)\n",
    "            CostofCakes.set(CakesPrice)\n",
    "            SC='₹',str('%f'%(199))\n",
    "            ServiceCharge.set(SC)\n",
    "            \n",
    "            St='₹',str('%f'%(PriceofDrinks+PriceofCakes+199))\n",
    "            SubTotal.set(St)\n",
    "            \n",
    "            Tax='₹',str('%f'%((PriceofDrinks+PriceofCakes+199)*0.05))\n",
    "            PaidTax.set(Tax)\n",
    "            \n",
    "            TT=(PriceofDrinks+PriceofCakes+199)*0.05\n",
    "            TC='₹',str('%f'%(PriceofDrinks+PriceofCakes+199+TT))\n",
    "            TotalCost.set(TC)\n",
    "                \n",
    "        def Reset():\n",
    "            PaidTax.set('')\n",
    "            SubTotal.set('')\n",
    "            TotalCost.set('')\n",
    "            CostofDrinks.set('')\n",
    "            CostofCakes.set('')\n",
    "            ServiceCharge.set('') \n",
    "            txtReceipt.delete(\"1.0\",END)\n",
    "            var1.set(0)\n",
    "            var2.set(0)\n",
    "            var3.set(0)\n",
    "            var4.set(0)\n",
    "            var5.set(0)\n",
    "            var6.set(0)\n",
    "            var7.set(0)\n",
    "            var8.set(0)\n",
    "            var9.set(0)\n",
    "            var10.set(0)\n",
    "            var11.set(0)\n",
    "            var12.set(0)\n",
    "            \n",
    "            E_m1.set('0')\n",
    "            E_m2.set('0')\n",
    "            E_m3.set('0')\n",
    "            E_m4.set('0')\n",
    "            E_m5.set('0')\n",
    "            E_m6.set('0')\n",
    "            E_m7.set('0')\n",
    "            E_m8.set('0')\n",
    "            E_m9.set('0')\n",
    "            E_m10.set('0')\n",
    "            E_m11.set('0')\n",
    "            E_m12.set('0')\n",
    "        \n",
    "            txtm1.configure(state=DISABLED)\n",
    "            txtm2.configure(state=DISABLED)\n",
    "            txtm3.configure(state=DISABLED)\n",
    "            txtm4.configure(state=DISABLED)\n",
    "            txtm5.configure(state=DISABLED)\n",
    "            txtm6.configure(state=DISABLED)\n",
    "            txtm7.configure(state=DISABLED)\n",
    "            txtm8.configure(state=DISABLED)\n",
    "            txtm9.configure(state=DISABLED)\n",
    "            txtm10.configure(state=DISABLED)\n",
    "            txtm11.configure(state=DISABLED)\n",
    "            txtm12.configure(state=DISABLED)\n",
    "            \n",
    "        def chkbutton_value():\n",
    "            if(var1.get()==1):\n",
    "                txtm1.configure(state=NORMAL)\n",
    "            elif var1.get()==0:\n",
    "                txtm1.configure(state=DISABLED)\n",
    "                E_m1.set('0')\n",
    "            if(var2.get()==1):\n",
    "                txtm2.configure(state=NORMAL)\n",
    "            elif var2.get()==0:\n",
    "                txtm2.configure(state=DISABLED)\n",
    "                E_m2.set('0')\n",
    "            if(var3.get()==1):\n",
    "                txtm3.configure(state=NORMAL)\n",
    "            elif var3.get()==0:\n",
    "                txtm3.configure(state=DISABLED)\n",
    "                E_m3.set('0')\n",
    "            if(var4.get()==1):\n",
    "                txtm4.configure(state=NORMAL)\n",
    "            elif var4.get()==0:\n",
    "                txtm4.configure(state=DISABLED)\n",
    "                E_m4.set('0')\n",
    "            if(var5.get()==1):\n",
    "                txtm5.configure(state=NORMAL)\n",
    "            elif var5.get()==0:\n",
    "                txtm5.configure(state=DISABLED)\n",
    "                E_m5.set('0')\n",
    "            if(var6.get()==1):\n",
    "                txtm6.configure(state=NORMAL)\n",
    "            elif var6.get()==0:\n",
    "                txtm6.configure(state=DISABLED)\n",
    "                E_m6.set('0')\n",
    "            if(var7.get()==1):\n",
    "                txtm7.configure(state=NORMAL)\n",
    "            elif var7.get()==0:\n",
    "                txtm7.configure(state=DISABLED)\n",
    "                E_m7.set('0')\n",
    "            if(var8.get()==1):\n",
    "                txtm8.configure(state=NORMAL)\n",
    "            elif var8.get()==0:\n",
    "                txtm8.configure(state=DISABLED)\n",
    "                E_m8.set('0')\n",
    "            if(var9.get()==1):\n",
    "                txtm9.configure(state=NORMAL)\n",
    "            elif var9.get()==0:\n",
    "                txtm9.configure(state=DISABLED)\n",
    "                E_m9.set('0')\n",
    "            if(var10.get()==1):\n",
    "                txtm10.configure(state=NORMAL)\n",
    "            elif var10.get()==0:\n",
    "                txtm10.configure(state=DISABLED)\n",
    "                E_m10.set('0')\n",
    "            if(var11.get()==1):\n",
    "                txtm11.configure(state=NORMAL)\n",
    "            elif var11.get()==0:\n",
    "                txtm11.configure(state=DISABLED)\n",
    "                E_m11.set('0')\n",
    "            if(var12.get()==1):\n",
    "                txtm12.configure(state=NORMAL)\n",
    "            elif var12.get()==0:\n",
    "                txtm12.configure(state=DISABLED)\n",
    "                E_m12.set('0')\n",
    "        #variable\n",
    "        E_m1=StringVar()\n",
    "        E_m2=StringVar()\n",
    "        E_m3=StringVar()\n",
    "        E_m4=StringVar()\n",
    "        E_m5=StringVar()\n",
    "        E_m6=StringVar()\n",
    "        E_m7=StringVar()\n",
    "        E_m8=StringVar()\n",
    "        E_m9=StringVar()\n",
    "        E_m10=StringVar()\n",
    "        E_m11=StringVar()\n",
    "        E_m12=StringVar()\n",
    "        \n",
    "        E_m1.set('0')\n",
    "        E_m2.set('0')\n",
    "        E_m3.set('0')\n",
    "        E_m4.set('0')\n",
    "        E_m5.set('0')\n",
    "        E_m6.set('0')\n",
    "        E_m7.set('0')\n",
    "        E_m8.set('0')\n",
    "        E_m9.set('0')\n",
    "        E_m10.set('0')\n",
    "        E_m11.set('0')\n",
    "        E_m12.set('0')\n",
    "        \n",
    "        DateofOrder=StringVar()\n",
    "        Receipt_Ref=StringVar()\n",
    "        PaidTax=StringVar()\n",
    "        SubTotal=StringVar()\n",
    "        TotalCost=StringVar()\n",
    "        CostofCakes=StringVar()\n",
    "        CostofDrinks=StringVar()\n",
    "        ServiceCharge=StringVar()\n",
    "        \n",
    "        DateofOrder.set(time.strftime('%d/%m/%Y'))\n",
    "        \n",
    "        \n",
    "        var1=IntVar()\n",
    "        var1.set('0')\n",
    "        m1=Checkbutton(f1aa,text='Latte \\t\\t\\t',variable=var1,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='orange4',bg='white',command=chkbutton_value).grid(row=0,column=0)\n",
    "        var2=IntVar()\n",
    "        var2.set('0')\n",
    "        m2=Checkbutton(f1aa,text='Flat White \\t\\t',variable=var2,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='orange4',bg='white',command=chkbutton_value).grid(row=1,column=0)\n",
    "        var3=IntVar()\n",
    "        var3.set('0')\n",
    "        m3=Checkbutton(f1aa,text='Cappuccino \\t\\t',variable=var3,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='orange4',bg='white',command=chkbutton_value).grid(row=2,column=0)\n",
    "        var4=IntVar()\n",
    "        var4.set('0')\n",
    "        m4=Checkbutton(f1aa,text='Espresso \\t\\t\\t',variable=var4,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='orange4',bg='white',command=chkbutton_value).grid(row=3,column=0)\n",
    "        var5=IntVar()\n",
    "        var5.set('0')\n",
    "        m5=Checkbutton(f1aa,text='White Hot Chocolate \\t',variable=var5,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='orange4',bg='white',command=chkbutton_value).grid(row=4,column=0)\n",
    "        var6=IntVar()\n",
    "        var6.set('0')\n",
    "        m6=Checkbutton(f1aa,text='Matcha Tea \\t\\t',variable=var6,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='palegreen2',bg='white',command=chkbutton_value).grid(row=5,column=0)\n",
    "        var7=IntVar()\n",
    "        var7.set('0')\n",
    "        m7=Checkbutton(f1ab,text='Chai \\t\\t\\t',variable=var7,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='palegreen2',bg='white',command=chkbutton_value).grid(row=0,column=0)\n",
    "        var8=IntVar()\n",
    "        var8.set('0')\n",
    "        m8=Checkbutton(f1ab,text='Tea Lemonade \\t\\t',variable=var8,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='palegreen2',bg='white',command=chkbutton_value).grid(row=1,column=0)\n",
    "        var9=IntVar()\n",
    "        var9.set('0')\n",
    "        m9=Checkbutton(f1ab,text='Cool Lime \\t\\t',variable=var9,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='palegreen2',bg='white',command=chkbutton_value).grid(row=2,column=0)\n",
    "        var10=IntVar()\n",
    "        var10.set('0')\n",
    "        m10=Checkbutton(f1ab,text='Vanilla Cake \\t\\t',variable=var10,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='pink',bg='white',command=chkbutton_value).grid(row=3,column=0)\n",
    "        var11=IntVar()\n",
    "        var11.set('0')\n",
    "        m11=Checkbutton(f1ab,text='Chocolate Cake \\t\\t',variable=var11,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='pink',bg='white',command=chkbutton_value).grid(row=4,column=0)\n",
    "        var12=IntVar()\n",
    "        var12.set('0')\n",
    "        m12=Checkbutton(f1ab,text='Strawberry and Vanilla Cake \\t',variable=var12,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='pink',bg='white',command=chkbutton_value).grid(row=5,column=0)\n",
    "        \n",
    "        \n",
    "                \n",
    "                \n",
    "        #Widget\n",
    "        txtm1=Entry(f1aa,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m1,state=DISABLED,bg='white')\n",
    "        txtm1.grid(row=0,column=1)\n",
    "        txtm2=Entry(f1aa,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m2,state=DISABLED,bg='white')\n",
    "        txtm2.grid(row=1,column=1)\n",
    "        txtm3=Entry(f1aa,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m3,state=DISABLED,bg='white')\n",
    "        txtm3.grid(row=2,column=1)\n",
    "        txtm4=Entry(f1aa,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m4,state=DISABLED,bg='white')\n",
    "        txtm4.grid(row=3,column=1)\n",
    "        txtm5=Entry(f1aa,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m5,state=DISABLED,bg='white')\n",
    "        txtm5.grid(row=4,column=1)\n",
    "        txtm6=Entry(f1aa,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m6,state=DISABLED,bg='white')\n",
    "        txtm6.grid(row=5,column=1)\n",
    "        txtm7=Entry(f1ab,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m7,state=DISABLED,bg='white')\n",
    "        txtm7.grid(row=0,column=1)\n",
    "        txtm8=Entry(f1ab,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m8,state=DISABLED,bg='white')\n",
    "        txtm8.grid(row=1,column=1)\n",
    "        txtm9=Entry(f1ab,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m9,state=DISABLED,bg='white')\n",
    "        txtm9.grid(row=2,column=1)\n",
    "        txtm10=Entry(f1ab,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m10,state=DISABLED,bg='white')\n",
    "        txtm10.grid(row=3,column=1)\n",
    "        txtm11=Entry(f1ab,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m11,state=DISABLED,bg='white')\n",
    "        txtm11.grid(row=4,column=1)\n",
    "        txtm12=Entry(f1ab,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m12,state=DISABLED,bg='white')\n",
    "        txtm12.grid(row=5,column=1)\n",
    "        #Info\n",
    "        lblReceipt=Label(ft2,font=('Bahnschrift',12,'bold'),text='Receipt:',bd=1,anchor='w')\n",
    "        lblReceipt.grid(row=0,column=0,sticky=W)\n",
    "        txtReceipt=Text(ft2,width=50,height=20,bd=1,font=('Segoe Print',12,'bold'))\n",
    "        txtReceipt.grid(row=1,column=0)\n",
    "        #Cost of Item\n",
    "        lblCostofDrinks=Label(f2aa,font=('Segoe Print',19,'bold'),text='Cost of Drinks \\t',bg='khaki1',fg='lightsalmon4',bd=1)\n",
    "        lblCostofDrinks.grid(row=0,column=0,sticky=W)\n",
    "        txtCostofDrinks=Entry(f2aa,font=('arial',16,'bold'),bd=1,bg='white',justify='left',textvariable=CostofDrinks,width=6)\n",
    "        txtCostofDrinks.grid(row=0,column=1,sticky=W)\n",
    "        \n",
    "        lblCostofCakes=Label(f2aa,font=('Segoe Print',19,'bold'),text='Cost of Cakes \\t',bg='khaki1',fg='lightsalmon4',bd=1)\n",
    "        lblCostofCakes.grid(row=1,column=0,sticky=W)\n",
    "        txtCostofCakes=Entry(f2aa,font=('arial',16,'bold'),bd=1,bg='white',justify='left',textvariable=CostofCakes,width=6)\n",
    "        txtCostofCakes.grid(row=1,column=1,sticky=W)\n",
    "        \n",
    "        lblServiceCharge=Label(f2aa,font=('Segoe Print',19,'bold'),text='Service Charges \\t',bg='khaki1',fg='lightsalmon4',bd=1)\n",
    "        lblServiceCharge.grid(row=2,column=0,sticky=W)\n",
    "        txtServiceCharge=Entry(f2aa,font=('arial',16,'bold'),bd=1,bg='white',justify='left',textvariable=ServiceCharge,width=6)\n",
    "        txtServiceCharge.grid(row=2,column=1,sticky=W)\n",
    "        #Payment Info\n",
    "        lblPaidTax=Label(f2ab,font=('Segoe Print',19,'bold'),text='Tax  \\t\\t',bg='khaki1',fg='lightsalmon4',bd=1)\n",
    "        lblPaidTax.grid(row=0,column=0,sticky=W)\n",
    "        txtPaidTax=Entry(f2ab,font=('arial',16,'bold'),bd=1,bg='white',justify='left',textvariable=PaidTax,width=8)\n",
    "        txtPaidTax.grid(row=0,column=1,sticky=W)\n",
    "        \n",
    "        lblSubTotal=Label(f2ab,font=('Segoe Print',19,'bold'),text='Sub Total  \\t\\t',bg='khaki1',fg='lightsalmon4',bd=1)\n",
    "        lblSubTotal.grid(row=1,column=0,sticky=W)\n",
    "        txtSubTotal=Entry(f2ab,font=('arial',16,'bold'),bd=1,bg='white',justify='left',textvariable=SubTotal,width=8)\n",
    "        txtSubTotal.grid(row=1,column=1,sticky=W)\n",
    "        \n",
    "        lblTotalCost=Label(f2ab,font=('Segoe Print',19,'bold'),text='Total Cost  \\t',bg='khaki1',fg='lightsalmon4',bd=1)\n",
    "        lblTotalCost.grid(row=2,column=0,sticky=W)\n",
    "        txtTotalCost=Entry(f2ab,font=('arial',16,'bold'),bd=1,bg='white',justify='left',textvariable=TotalCost,width=8)\n",
    "        txtTotalCost.grid(row=2,column=1,sticky=W)\n",
    "        \n",
    "        PaidTax.set('')\n",
    "        SubTotal.set('')\n",
    "        TotalCost.set('')\n",
    "        CostofDrinks.set('')\n",
    "        CostofCakes.set('')\n",
    "        ServiceCharge.set('')\n",
    "        #Button\n",
    "        btnTotal=Button(fb2,padx=16,pady=1,bd=1,fg='lightsalmon4',bg='white',font=('Ink Free',16,'bold'),command=CostofItem,width=5,text='Total').grid(row=0,column=0)\n",
    "        btnReceipt=Button(fb2,padx=16,pady=1,bd=1,fg='lightsalmon4',bg='white',font=('Ink Free',16,'bold'),command=Receipt,width=5,text='Receipt').grid(row=0,column=1)\n",
    "        btnReset=Button(fb2,padx=16,pady=1,bd=1,fg='lightsalmon4',bg='white',font=('Ink Free',16,'bold'),command=Reset,width=5,text='Reset').grid(row=0,column=2)\n",
    "        btnExit=Button(fb2,padx=16,pady=1,bd=1,fg='lightsalmon4',bg='white',font=('Ink Free',16,'bold'),command=qExit,width=5,text='Exit').grid(row=0,column=3)\n",
    "    else:\n",
    "        def qExit():\n",
    "            qExit=messagebox.askyesno(\"Quit System\",\"Willst du das System beenden?\")\n",
    "            if qExit>0:\n",
    "                root.destroy()\n",
    "                return\n",
    "        def Receipt():\n",
    "            txtReceipt.delete(\"1.0\",END)\n",
    "            x=random.randint(10900,500876)\n",
    "            randomRef=str(x)\n",
    "            Receipt_Ref.set(\"RCC\"+randomRef)\n",
    "            txtReceipt.insert(END,'Rechnungs nr.:\\t\\t'+Receipt_Ref.get()+'\\t\\t'+DateofOrder.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Produkt\\t\\t\\t'+'Menge \\n')\n",
    "            txtReceipt.insert(END,'Latte\\t\\t\\t'+E_m1.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Flat White\\t\\t\\t'+E_m2.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Cappuccino\\t\\t\\t'+E_m3.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Espresso\\t\\t\\t'+E_m4.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Heiße Schokolade\\t\\t\\t'+E_m5.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Matchatee\\t\\t\\t'+E_m6.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Chai\\t\\t\\t'+E_m7.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Tee Limonade\\t\\t\\t'+E_m8.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Cool Lime\\t\\t\\t'+E_m9.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Vanillekuchen\\t\\t\\t'+E_m10.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Schokoladenkuchen\\t\\t\\t'+E_m11.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Erdbeer-und Vanillekuchen\\t\\t\\t'+E_m12.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Preis der Getränke:\\t'+CostofDrinks.get()+'\\t   Steurung:\\t'+PaidTax.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Preis der Kuchen:\\t'+CostofCakes.get()+'\\t  Preis(Brutto):\\t'+SubTotal.get()+'\\n')\n",
    "            txtReceipt.insert(END,'Zusätzliche Kosten\\t'+CostofDrinks.get()+'\\t   Preis(Netto):\\t'+TotalCost.get()+'\\n')\n",
    "            \n",
    "        def CostofItem():\n",
    "            i1=float(E_m1.get())\n",
    "            i2=float(E_m2.get())\n",
    "            i3=float(E_m3.get())\n",
    "            i4=float(E_m4.get())\n",
    "            i5=float(E_m5.get())\n",
    "            i6=float(E_m6.get())\n",
    "            i7=float(E_m7.get())\n",
    "            i8=float(E_m8.get())\n",
    "            i9=float(E_m9.get())\n",
    "            i10=float(E_m10.get())\n",
    "            i11=float(E_m11.get())\n",
    "            i12=float(E_m12.get())\n",
    "            \n",
    "            PriceofDrinks=(i1*2.3)+(i2*2.45)+(i3*2.1)+(i4*1.17)+(i5*3.5)+(i6*4)+(i7*1.4)+(i8*1.63)+(i9*0.93)\n",
    "            PriceofCakes=(i10*8.4)+(i11*10)+(i12*14)\n",
    "            \n",
    "            DrinksPrice='€',str('%.2f'%(PriceofDrinks))\n",
    "            CakesPrice='€',str('%.2f'%(PriceofCakes))\n",
    "            CostofDrinks.set(DrinksPrice)\n",
    "            CostofCakes.set(CakesPrice)\n",
    "            SC='€',str('%f'%(2.33))\n",
    "            ServiceCharge.set(SC)\n",
    "            \n",
    "            St='€',str('%f'%(PriceofDrinks+PriceofCakes+2.33))\n",
    "            SubTotal.set(St)\n",
    "            \n",
    "            Tax='€',str('%f'%((PriceofDrinks+PriceofCakes+2.33)*0.05))\n",
    "            PaidTax.set(Tax)\n",
    "            \n",
    "            TT=(PriceofDrinks+PriceofCakes+2.33)*0.05\n",
    "            TC='€',str('%f'%(PriceofDrinks+PriceofCakes+2.33+TT))\n",
    "            TotalCost.set(TC)\n",
    "                \n",
    "        def Reset():\n",
    "            PaidTax.set('')\n",
    "            SubTotal.set('')\n",
    "            TotalCost.set('')\n",
    "            CostofDrinks.set('')\n",
    "            CostofCakes.set('')\n",
    "            ServiceCharge.set('') \n",
    "            txtReceipt.delete(\"1.0\",END)\n",
    "            var1.set(0)\n",
    "            var2.set(0)\n",
    "            var3.set(0)\n",
    "            var4.set(0)\n",
    "            var5.set(0)\n",
    "            var6.set(0)\n",
    "            var7.set(0)\n",
    "            var8.set(0)\n",
    "            var9.set(0)\n",
    "            var10.set(0)\n",
    "            var11.set(0)\n",
    "            var12.set(0)\n",
    "            \n",
    "            E_m1.set('0')\n",
    "            E_m2.set('0')\n",
    "            E_m3.set('0')\n",
    "            E_m4.set('0')\n",
    "            E_m5.set('0')\n",
    "            E_m6.set('0')\n",
    "            E_m7.set('0')\n",
    "            E_m8.set('0')\n",
    "            E_m9.set('0')\n",
    "            E_m10.set('0')\n",
    "            E_m11.set('0')\n",
    "            E_m12.set('0')\n",
    "        \n",
    "            txtm1.configure(state=DISABLED)\n",
    "            txtm2.configure(state=DISABLED)\n",
    "            txtm3.configure(state=DISABLED)\n",
    "            txtm4.configure(state=DISABLED)\n",
    "            txtm5.configure(state=DISABLED)\n",
    "            txtm6.configure(state=DISABLED)\n",
    "            txtm7.configure(state=DISABLED)\n",
    "            txtm8.configure(state=DISABLED)\n",
    "            txtm9.configure(state=DISABLED)\n",
    "            txtm10.configure(state=DISABLED)\n",
    "            txtm11.configure(state=DISABLED)\n",
    "            txtm12.configure(state=DISABLED)\n",
    "            \n",
    "        def chkbutton_value():\n",
    "            if(var1.get()==1):\n",
    "                txtm1.configure(state=NORMAL)\n",
    "            elif var1.get()==0:\n",
    "                txtm1.configure(state=DISABLED)\n",
    "                E_m1.set('0')\n",
    "            if(var2.get()==1):\n",
    "                txtm2.configure(state=NORMAL)\n",
    "            elif var2.get()==0:\n",
    "                txtm2.configure(state=DISABLED)\n",
    "                E_m2.set('0')\n",
    "            if(var3.get()==1):\n",
    "                txtm3.configure(state=NORMAL)\n",
    "            elif var3.get()==0:\n",
    "                txtm3.configure(state=DISABLED)\n",
    "                E_m3.set('0')\n",
    "            if(var4.get()==1):\n",
    "                txtm4.configure(state=NORMAL)\n",
    "            elif var4.get()==0:\n",
    "                txtm4.configure(state=DISABLED)\n",
    "                E_m4.set('0')\n",
    "            if(var5.get()==1):\n",
    "                txtm5.configure(state=NORMAL)\n",
    "            elif var5.get()==0:\n",
    "                txtm5.configure(state=DISABLED)\n",
    "                E_m5.set('0')\n",
    "            if(var6.get()==1):\n",
    "                txtm6.configure(state=NORMAL)\n",
    "            elif var6.get()==0:\n",
    "                txtm6.configure(state=DISABLED)\n",
    "                E_m6.set('0')\n",
    "            if(var7.get()==1):\n",
    "                txtm7.configure(state=NORMAL)\n",
    "            elif var7.get()==0:\n",
    "                txtm7.configure(state=DISABLED)\n",
    "                E_m7.set('0')\n",
    "            if(var8.get()==1):\n",
    "                txtm8.configure(state=NORMAL)\n",
    "            elif var8.get()==0:\n",
    "                txtm8.configure(state=DISABLED)\n",
    "                E_m8.set('0')\n",
    "            if(var9.get()==1):\n",
    "                txtm9.configure(state=NORMAL)\n",
    "            elif var9.get()==0:\n",
    "                txtm9.configure(state=DISABLED)\n",
    "                E_m9.set('0')\n",
    "            if(var10.get()==1):\n",
    "                txtm10.configure(state=NORMAL)\n",
    "            elif var10.get()==0:\n",
    "                txtm10.configure(state=DISABLED)\n",
    "                E_m10.set('0')\n",
    "            if(var11.get()==1):\n",
    "                txtm11.configure(state=NORMAL)\n",
    "            elif var11.get()==0:\n",
    "                txtm11.configure(state=DISABLED)\n",
    "                E_m11.set('0')\n",
    "            if(var12.get()==1):\n",
    "                txtm12.configure(state=NORMAL)\n",
    "            elif var12.get()==0:\n",
    "                txtm12.configure(state=DISABLED)\n",
    "                E_m12.set('0')\n",
    "        #variable\n",
    "        E_m1=StringVar()\n",
    "        E_m2=StringVar()\n",
    "        E_m3=StringVar()\n",
    "        E_m4=StringVar()\n",
    "        E_m5=StringVar()\n",
    "        E_m6=StringVar()\n",
    "        E_m7=StringVar()\n",
    "        E_m8=StringVar()\n",
    "        E_m9=StringVar()\n",
    "        E_m10=StringVar()\n",
    "        E_m11=StringVar()\n",
    "        E_m12=StringVar()\n",
    "        \n",
    "        E_m1.set('0')\n",
    "        E_m2.set('0')\n",
    "        E_m3.set('0')\n",
    "        E_m4.set('0')\n",
    "        E_m5.set('0')\n",
    "        E_m6.set('0')\n",
    "        E_m7.set('0')\n",
    "        E_m8.set('0')\n",
    "        E_m9.set('0')\n",
    "        E_m10.set('0')\n",
    "        E_m11.set('0')\n",
    "        E_m12.set('0')\n",
    "        \n",
    "        DateofOrder=StringVar()\n",
    "        Receipt_Ref=StringVar()\n",
    "        PaidTax=StringVar()\n",
    "        SubTotal=StringVar()\n",
    "        TotalCost=StringVar()\n",
    "        CostofCakes=StringVar()\n",
    "        CostofDrinks=StringVar()\n",
    "        ServiceCharge=StringVar()\n",
    "        \n",
    "        DateofOrder.set(time.strftime('%d/%m/%Y'))\n",
    "        \n",
    "        \n",
    "        var1=IntVar()\n",
    "        var1.set('0')\n",
    "        m1=Checkbutton(f1aa,text='Latte \\t\\t\\t',variable=var1,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='orange4',bg='white',command=chkbutton_value).grid(row=0,column=0)\n",
    "        var2=IntVar()\n",
    "        var2.set('0')\n",
    "        m2=Checkbutton(f1aa,text='Flat White \\t\\t',variable=var2,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='orange4',bg='white',command=chkbutton_value).grid(row=1,column=0)\n",
    "        var3=IntVar()\n",
    "        var3.set('0')\n",
    "        m3=Checkbutton(f1aa,text='Cappuccino \\t\\t',variable=var3,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='orange4',bg='white',command=chkbutton_value).grid(row=2,column=0)\n",
    "        var4=IntVar()\n",
    "        var4.set('0')\n",
    "        m4=Checkbutton(f1aa,text='Espresso \\t\\t\\t',variable=var4,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='orange4',bg='white',command=chkbutton_value).grid(row=3,column=0)\n",
    "        var5=IntVar()\n",
    "        var5.set('0')\n",
    "        m5=Checkbutton(f1aa,text='Heiße Schokolade \\t\\t',variable=var5,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='orange4',bg='white',command=chkbutton_value).grid(row=4,column=0)\n",
    "        var6=IntVar()\n",
    "        var6.set('0')\n",
    "        m6=Checkbutton(f1aa,text='Matchatee \\t\\t',variable=var6,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='palegreen2',bg='white',command=chkbutton_value).grid(row=5,column=0)\n",
    "        var7=IntVar()\n",
    "        var7.set('0')\n",
    "        m7=Checkbutton(f1ab,text='Chai \\t\\t\\t',variable=var7,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='palegreen2',bg='white',command=chkbutton_value).grid(row=0,column=0)\n",
    "        var8=IntVar()\n",
    "        var8.set('0')\n",
    "        m8=Checkbutton(f1ab,text='Tee Limonade \\t\\t',variable=var8,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='palegreen2',bg='white',command=chkbutton_value).grid(row=1,column=0)\n",
    "        var9=IntVar()\n",
    "        var9.set('0')\n",
    "        m9=Checkbutton(f1ab,text='Cool Lime \\t\\t',variable=var9,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='palegreen2',bg='white',command=chkbutton_value).grid(row=2,column=0)\n",
    "        var10=IntVar()\n",
    "        var10.set('0')\n",
    "        m10=Checkbutton(f1ab,text='Vanillekuchen \\t\\t',variable=var10,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='pink',bg='white',command=chkbutton_value).grid(row=3,column=0)\n",
    "        var11=IntVar()\n",
    "        var11.set('0')\n",
    "        m11=Checkbutton(f1ab,text='Schokoladenkuchen \\t\\t',variable=var11,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='pink',bg='white',command=chkbutton_value).grid(row=4,column=0)\n",
    "        var12=IntVar()\n",
    "        var12.set('0')\n",
    "        m12=Checkbutton(f1ab,text='Erdbeer-und Vanillekuchen \\t',variable=var12,onvalue=1,offvalue=0,font=('gabriola',18,'bold'),fg='pink',bg='white',command=chkbutton_value).grid(row=5,column=0)\n",
    "        \n",
    "        \n",
    "                \n",
    "                \n",
    "        #Widget\n",
    "        txtm1=Entry(f1aa,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m1,state=DISABLED,bg='white')\n",
    "        txtm1.grid(row=0,column=1)\n",
    "        txtm2=Entry(f1aa,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m2,state=DISABLED,bg='white')\n",
    "        txtm2.grid(row=1,column=1)\n",
    "        txtm3=Entry(f1aa,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m3,state=DISABLED,bg='white')\n",
    "        txtm3.grid(row=2,column=1)\n",
    "        txtm4=Entry(f1aa,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m4,state=DISABLED,bg='white')\n",
    "        txtm4.grid(row=3,column=1)\n",
    "        txtm5=Entry(f1aa,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m5,state=DISABLED,bg='white')\n",
    "        txtm5.grid(row=4,column=1)\n",
    "        txtm6=Entry(f1aa,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m6,state=DISABLED,bg='white')\n",
    "        txtm6.grid(row=5,column=1)\n",
    "        txtm7=Entry(f1ab,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m7,state=DISABLED,bg='white')\n",
    "        txtm7.grid(row=0,column=1)\n",
    "        txtm8=Entry(f1ab,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m8,state=DISABLED,bg='white')\n",
    "        txtm8.grid(row=1,column=1)\n",
    "        txtm9=Entry(f1ab,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m9,state=DISABLED,bg='white')\n",
    "        txtm9.grid(row=2,column=1)\n",
    "        txtm10=Entry(f1ab,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m10,state=DISABLED,bg='white')\n",
    "        txtm10.grid(row=3,column=1)\n",
    "        txtm11=Entry(f1ab,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m11,state=DISABLED,bg='white')\n",
    "        txtm11.grid(row=4,column=1)\n",
    "        txtm12=Entry(f1ab,font=('arial',16,'bold'),bd=2,width=4,justify='left',textvariable=E_m12,state=DISABLED,bg='white')\n",
    "        txtm12.grid(row=5,column=1)\n",
    "        #Info\n",
    "        lblReceipt=Label(ft2,font=('Bahnschrift',12,'bold'),text='Quittung:',bd=1,anchor='w')\n",
    "        lblReceipt.grid(row=0,column=0,sticky=W)\n",
    "        txtReceipt=Text(ft2,width=50,height=20,bd=1,font=('Segoe Print',12,'bold'))\n",
    "        txtReceipt.grid(row=1,column=0)\n",
    "        #Cost of Item\n",
    "        lblCostofDrinks=Label(f2aa,font=('Segoe Print',19,'bold'),text='Preis der Getränke \\t',bg='khaki1',fg='lightsalmon4',bd=1)\n",
    "        lblCostofDrinks.grid(row=0,column=0,sticky=W)\n",
    "        txtCostofDrinks=Entry(f2aa,font=('arial',16,'bold'),bd=1,bg='white',justify='left',textvariable=CostofDrinks,width=6)\n",
    "        txtCostofDrinks.grid(row=0,column=1,sticky=W)\n",
    "        \n",
    "        lblCostofCakes=Label(f2aa,font=('Segoe Print',19,'bold'),text='Preis der Kuchen \\t',bg='khaki1',fg='lightsalmon4',bd=1)\n",
    "        lblCostofCakes.grid(row=1,column=0,sticky=W)\n",
    "        txtCostofCakes=Entry(f2aa,font=('arial',16,'bold'),bd=1,bg='white',justify='left',textvariable=CostofCakes,width=6)\n",
    "        txtCostofCakes.grid(row=1,column=1,sticky=W)\n",
    "        \n",
    "        lblServiceCharge=Label(f2aa,font=('Segoe Print',19,'bold'),text='Zusätzliche Kosten \\t',bg='khaki1',fg='lightsalmon4',bd=1)\n",
    "        lblServiceCharge.grid(row=2,column=0,sticky=W)\n",
    "        txtServiceCharge=Entry(f2aa,font=('arial',16,'bold'),bd=1,bg='white',justify='left',textvariable=ServiceCharge,width=6)\n",
    "        txtServiceCharge.grid(row=2,column=1,sticky=W)\n",
    "        #Payment Info\n",
    "        lblPaidTax=Label(f2ab,font=('Segoe Print',19,'bold'),text='Steurung  \\t\\t',bg='khaki1',fg='lightsalmon4',bd=1)\n",
    "        lblPaidTax.grid(row=0,column=0,sticky=W)\n",
    "        txtPaidTax=Entry(f2ab,font=('arial',16,'bold'),bd=1,bg='white',justify='left',textvariable=PaidTax,width=8)\n",
    "        txtPaidTax.grid(row=0,column=1,sticky=W)\n",
    "        \n",
    "        lblSubTotal=Label(f2ab,font=('Segoe Print',19,'bold'),text='Preis(Brutto)  \\t',bg='khaki1',fg='lightsalmon4',bd=1)\n",
    "        lblSubTotal.grid(row=1,column=0,sticky=W)\n",
    "        txtSubTotal=Entry(f2ab,font=('arial',16,'bold'),bd=1,bg='white',justify='left',textvariable=SubTotal,width=8)\n",
    "        txtSubTotal.grid(row=1,column=1,sticky=W)\n",
    "        \n",
    "        lblTotalCost=Label(f2ab,font=('Segoe Print',19,'bold'),text='Preis(Netto) \\t',bg='khaki1',fg='lightsalmon4',bd=1)\n",
    "        lblTotalCost.grid(row=2,column=0,sticky=W)\n",
    "        txtTotalCost=Entry(f2ab,font=('arial',16,'bold'),bd=1,bg='white',justify='left',textvariable=TotalCost,width=8)\n",
    "        txtTotalCost.grid(row=2,column=1,sticky=W)\n",
    "        \n",
    "        PaidTax.set('')\n",
    "        SubTotal.set('')\n",
    "        TotalCost.set('')\n",
    "        CostofDrinks.set('')\n",
    "        CostofCakes.set('')\n",
    "        ServiceCharge.set('')\n",
    "        #Button\n",
    "        btnTotal=Button(fb2,padx=16,pady=1,bd=1,fg='lightsalmon4',bg='white',font=('Ink Free',16,'bold'),command=CostofItem,width=5,text='Rechnen').grid(row=0,column=0)\n",
    "        btnReceipt=Button(fb2,padx=16,pady=1,bd=1,fg='lightsalmon4',bg='white',font=('Ink Free',16,'bold'),command=Receipt,width=5,text='Quittung').grid(row=0,column=1)\n",
    "        btnReset=Button(fb2,padx=16,pady=1,bd=1,fg='lightsalmon4',bg='white',font=('Ink Free',16,'bold'),command=Reset,width=5,text='Neustart').grid(row=0,column=2)\n",
    "        btnExit=Button(fb2,padx=16,pady=1,bd=1,fg='lightsalmon4',bg='white',font=('Ink Free',16,'bold'),command=qExit,width=5,text='Aus').grid(row=0,column=3)\n",
    "        \n",
    "    root.mainloop()\n",
    "print('By Default Language is German/ Deutsch wird automatisch gewählt')\n",
    "print('Enter E or e for English / geben Sie D oer d für deutsch ein')\n",
    "n=input()\n",
    "system(n)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b4446cb8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bf095254",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "36a08606",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
